### ISSUE TITLE
[Bug]: dida365 not working

### ISSUE THREAD

**Issue by mingzhao2019** [mslxl/ScoopIt#7]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

dida365

### Expected/Current Behaviour

when downloading dida365 for version 6.0.1.0, it only downloaded a 'download' file, and then shows 'exe is not found'. In the official website I tried to download dida365, it redirects me to this link https://cdn.dida365.cn/download/win64/dida_win_setup_release_x64_6010.exe

![image](https://github.com/mslxl/ScoopIt/assets/46117941/5129b118-34d5-4cfd-922e-b07a60310eb9)

![image](https://github.com/mslxl/ScoopIt/assets/46117941/22f23af9-3bf4-4ea1-8926-5aab0516ccb0)

### Steps to Reproduce

```console
PS C:\Users\mingz> scoop install dida365
Installing 'dida365' (6.0.1.0) [64bit] from 'mslxl' bucket
download (16.0 MB) [==========================================================================================] 100%
Checking hash of download ... ok.
Linking C:\Scoop\apps\dida365\current => C:\Scoop\apps\dida365\6.0.1.0
Creating shortcut for 滴答清单 (TickTick.exe) failed: Couldn't find C:\Scoop\apps\dida365\current\TickTick.exe
'dida365' (6.0.1.0) was installed successfully!
```

### Possible Solution

when downloading dida365 for version 6.0.1.0, it only downloaded a 'download' file, and then shows 'exe is not found'. In the official website I tried to download dida365, it redirects me to this link https://cdn.dida365.cn/download/win64/dida_win_setup_release_x64_6010.exe

### Scoop and Buckets Version

```console
PS C:\Users\mingz> scoop --version
Current Scoop version:
716b6db3 (HEAD -> master, tag: v0.5.0, origin/master, origin/HEAD) chore(release): Bump to version 0.5.0 (#6035)

'main' bucket:
e4cad1acf (HEAD -> master, origin/master, origin/HEAD) terraform: Update to version 1.9.2

'extras' bucket:
07c6df282 (HEAD -> master, origin/master, origin/HEAD) tabby: Update to version 1.0.209

'sysinternals' bucket:
56aa57d (HEAD -> main, origin/main, origin/HEAD) sysinternals-suite: Update to version 2024.06.20

'dorado' bucket:
ec72272d (HEAD -> master, origin/master, origin/HEAD) moonbit: Update to download explicit versioned artifacts

'mingzhao2019' bucket:
4039184 (HEAD -> master, origin/master, origin/HEAD) Delete bucket/dida365.json

'mslxl' bucket:
fb9427b (HEAD -> master, origin/master, origin/HEAD) kmonad-git: Update to version 97a3dea051a3565e97f2bdde60473a2d78182b07

'scoopet' bucket:
ae3fd95 (HEAD -> master, origin/master, origin/HEAD) feishu: Update to version 7.21.6

'winapps' bucket:
bd933f7 (HEAD -> master, origin/master, origin/HEAD) wps: Update to version 12.1.0.17147
```

### Scoop Config

```console
PS C:\Users\mingz> scoop config

last_update                       aria2-enabled scoop_branch scoop_repo
-----------                       ------------- ------------ ----------
2024-07-10T15:40:08.6327234+03:00         False master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS C:\Users\mingz> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.22621.3880
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.3880
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by mslxl** [comment]
Scoop will check the file extension first now, so it can be fixed by renaming its downloaded file.

Also, I noticed that a shortcut cannot be created with the name "滴答清单". It seems to be an upstream bug related to character encoding, but I haven't got much time to track the bug. Therefore, I renamed it to "Dida365" to avoid the problem and prevent any confusion with [TickTick (international)](https://ticktick.com/?language=en_US).
